"""Adding TMDB enum to enum_dbid_name

Revision ID: 95bb7d0dbe69
Revises: b82b375466
Create Date: 2017-09-30 20:32:38.477805

"""

# revision identifiers, used by Alembic.
revision = '95bb7d0dbe69'
down_revision = 'b82b375466'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, MetaData
import config


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #Just a warning that this is one way!
    op.execute('COMMIT')  # See https://bitbucket.org/zzzeek/alembic/issue/123
    op.execute('ALTER TYPE enum_dbid_name ADD VALUE \'TMDB\'')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
